FROM python:3.12-slim
 
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1
 
WORKDIR /app
 
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/calls/*
 
COPY requirements_api.txt .
RUN pip install --no-cache-dir -r requirements_api.txt
 
# main.py está em app/api/main.py no projeto
COPY app/api/main.py .
 
EXPOSE 8000
 
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]