INSERT INTO aneel_dominio_indicadores_indqual (indicator_code, indicator_description) VALUES
('AREA', 'Área do conj., expressa em km2, correspondente a área geogr. e não a área elétr.'),
('AREAT', 'Área do conjunto em km2'),
('CM', 'Encargo de uso do sistema de distribuição aplicado à unidade cons. (mensal)'),
('CMA', 'Encargo de uso do sistema de distribuição aplicado à unidade consumidora (anual)'),
('CMM', 'Consumo médio mensal, em MWh, média aritmética simples do último ano, excluin-'),
('CMMT', 'Consumo médio mensal em MWh'),
('CMMTCO', 'Energia cons comercial nos últimos 12 meses (ano móvel) MT e BT'),
('CMMTIN', 'Energia cons industrial nos últimos 12 meses (ano móvel)  MT e BT'),
('CMMTOU', 'Energia cons outras classes nos últimos 12 meses (ano móvel) MT e BT'),
('CMMTRE', 'Energia cons residencial nos últimos 12 meses (ano móvel) MT e BT'),
('CMMTRU', 'Energia cons rural nos últimos 12 meses (ano móvel) MT e BT'),
('CMT', 'Encargo de uso do sistema de distribuição aplicado à unidade cons. (trimestral)'),
('CODCLSUC', 'Código da Classe da Unidade Consumidora'),
('CODCLSUCA', 'Código da Classe da Unidade Consumidora'),
('CODCLSUCT', 'Código da Classe da Unidade Consumidora'),
('CODMUNUC', 'Código do Munícipio do Consumidor'),
('CODMUNUCA', 'Código do Munícipio do Consumidor'),
('CODMUNUCT', 'Código do Munícipio do Consumidor'),
('COMPCONF', 'Compensação de UC atendida fora dos limites previstos de DRP ou DRC'),
('COMPCONT', 'Compensação pela violação do DIC, FIC ou DMIC'),
('COMPCONTA', 'Compensação pela violação do DIC, FIC ou DMIC'),
('COMPCONTT', 'Compensação pela violação do DIC, FIC ou DMIC'),
('CRAFEDMED', 'Créd. Prazo Viol. de solicitações de aferição dos medidores (art. 137)'),
('CRANPROJ', 'Créd. Prazo Viol. de informação do resultado da análise do projeto (art. 27-B)'),
('CRCMSNOBRA', 'Créd. Prazo Viol. de Comissionamento das obras. (art. 37)'),
('CRESTPROJ', 'Créd. Prazo Viol. por estudos, orçamentos e projetos por obras (art. 32)'),
('CRINFORM', 'Créd. Prazo Viol. de informação da relação dos atendimentos (art. 199)'),
('CRLIGA', 'Créd. Prazo Viol. por ligação de unidade consumidora do grupo A (art. 31)'),
('CRLIGBRR', 'Créditos cedidos por ligação de consumidor do grupo B em área rural (art. 31)'),
('CRLIGBUB', 'Créd. Prazo Viol. por ligação de consumidor do grupo B em área urbana (art. 31)'),
('CRNVCMSN', 'Créd. Prazo Viol. de Novo comissionamento quando de reprovação. (art. 37)'),
('CROBGERAIS', 'Créd. Prazo Viol. de Conclusão de obra não abrang. nos inc. I e II do art. 34.'),
('CROBRA', 'Créd. Prazo Viol. por Início das Obras (art. 34)'),
('CROBRAPRIM', 'Créd. Prazo Viol. de Conclusão das obras de até 1 km na rede prim. (art. 34)'),
('CROBRASEC', 'Créd. Prazo Viol. de Conclusão das obras na rede tensão secundária. (art. 34)'),
('CRPGTORSC', 'Créd. Prazo Viol. de ressarc. por meio do pgto, conserto ou subst. (art. 208)'),
('CRRCLCOBR', 'Créd. Prazo Viol. de reclamação de cobrança ou devol. de diferenças (art. 133)'),
('CRRCLDANO', 'Créd. Prazo Viol. de solução ref. à danos não elétricos reclamados (art. 197)'),
('CRRCLVISTC', 'Créd. Prazo Viol. de solução de reclamação com visita técnica (art. 197)'),
('CRREANPROJ', 'Créd. Prazo Viol. de reanálise do projeto por falta de informação (art. 27-B)'),
('CRRELIGIDV', 'Créd. Prazo Viol. de religação por suspensão indevida do fornec. (art. 176)'),
('CRRELNORRR', 'Créd. Prazo Viol. de religação em área rural (art. 176)'),
('CRRELNORUB', 'Créd. Prazo Viol. de religação em área urbana (art. 176)'),
('CRRELURGRR', 'Créd. Prazo Viol. de religação de emergência em área rural (art. 176)'),
('CRRELURGUB', 'Créd. Prazo Viol. de religação de emergência em área urbana (art. 176)'),
('CRRESULRSC', 'Créd. Prazo Viol. de resultado da solicitação de ressarcimento (art. 207)'),
('CRSUBSTMED', 'Créditos cedidos por substituição do medidor com defeito (art. 115)'),
('CRVISTRR', 'Créd. Prazo Viol. por vistoria de unidade consumidora de área rural (art. 30)'),
('CRVISTUB', 'Créd. Prazo Viol. por vistoria de unidade consumidora de área urbana (art. 30)'),
('CRVRFRESFR', 'Créd. Prazo Viol. de verif. de equip. de resfriamento por ressarc. (art. 206)'),
('CRVRFRSC', 'Créd. Prazo Viol. de verif. de equip. por ressarc. de dano elétrico (art. 206)'),
('DEC', 'Duração Equivalente de Interrupção por Unidade Consumidora - 3 Min.'),
('DEC1', 'Duração Equivalente de Interrupção por Unidade Consumidora - 1 Min.'),
('DEC1I', 'Duração Equivalente de Interrupção por Unid. Cons. Decor.Rede Própria - 1 Min'),
('DEC1R', 'Duração Equivalente de Interrupção por Unidade Consumidora (Racion.)- 1 Min.'),
('DEC1X', 'Duração Equivalente de Interrupção por Unid. Cons. Fat. Externos - 1 Min.'),
('DECI', 'Duração Equivalente de Interrupção por Unid. Cons. Decor. Rede Própia - 3 Min.'),
('DECINC', 'DEC de interrup. origem interna ao Sist. de Dist. não progr. e ocor. Dia Crítico'),
('DECIND', 'DEC interrup origem interna, não programada e não expurgavel'),
('DECINE', 'DEC interrup. origem interna, não progr. e ocor. Sit. Emerg, n ocor critico.'),
('DECINO', 'DEC interrup. origem interna não progr. Racionamento e ONS, n ocor dia critico.'),
('DECIP', 'DEC de interrupção de origem interna ao Sist. de Dist. e programada'),
('DECIPC', 'DEC interrup. origem inter. ao sist distr, prog. e ocorr. em dia crítico'),
('DECR', 'Duração Equivalente de Interrupção por Unidade Consumidora (Racion.)- 3 Min.'),
('DECX', 'Duração Equivalente de Interrupção por Unid. Cons. Decor. Fat. Externos - 3 Min.'),
('DECXN', 'DEC de interrupção de origem externa ao Sist. de Dist. e não programada'),
('DECXNC', 'DEC interrup. origem ext. ao sist distr, não prog. e ocorr. em dia crítico'),
('DECXP', 'DEC de interrupção de origem externa ao Sist. de Dist. e programada'),
('DECXPC', 'DEC interrup. origem ext. ao sist distr, prog. e ocorr. em dia crítico'),
('DIADEBPDO', 'Dias Debitados - Próprio Doença'),
('DIADEBPTJ', 'Dias Debitados - Próprio Trajeto'),
('DIADEBPTP', 'Dias Debitados - Próprio Típico'),
('DIADEBTTP', 'Dias Debitados - Terceirizado Típico'),
('DIAPRDPDO', 'Dias Perdidos - Próprio Doença'),
('DIAPRDPTJ', 'Dias Perdidos - Próprio Trajeto'),
('DIAPRDPTP', 'Dias Perdidos - Próprio Típico'),
('DIAPRDTTP', 'Dias Perdidos - Terceirizado Típico'),
('DICVLD', 'Valor apurado do indicador DIC'),
('DICVLDA', 'Valor apurado do indicador DIC'),
('DICVLDT', 'Valor apurado do indicador DIC'),
('DMICVLD', 'Valor apurado do indicador DMIC'),
('DMICVLDA', 'Valor apurado do indicador DMIC violado'),
('DMICVLDT', 'Valor apurado do indicador DMIC violado'),
('DRC', 'Duração Relativa da Transgressão Máxima de Tensão Crítica Mensal'),
('DRCT', 'Duração Relativa da Transgressão Máxima de Tensão Crítica'),
('DRCVLD', 'Valor apurado do indicador DRC violado'),
('DRP', 'Duração Relativa da Transgressão Máxima de Tensão Precária Mensal'),
('DRPT', 'Duração Relativa da Transgressão Máxima de Tensão Precária'),
('DRPVLD', 'Valor apurado do indicador DRP violado'),
('ERP', 'Extensão de rede primária com nível de tensão inferior a 69kV, em km'),
('ERPT', 'Extensão de Rede Primária em km'),
('ERPTRU', 'Ext de rede de MT que atendem a área rur, redes próp e redes particulares'),
('ERPTUR', 'Ext de rede de MT que atendem a área urb, redes próp e redes particulares'),
('FEC', 'Freqüência Equivalente de Interrupção por Unidade Consumidora - 3 Min.'),
('FEC1', 'Freqüencia Equivalente de Interrupção por Unidade Consumidora - 1 Min.'),
('FEC1I', 'Freqüência Equivalente de Interrupção por Unid. Cons. Decor.Rede Própria - 1 Min'),
('FEC1R', 'Freqüência Equivalente de Interrupção por Unidade Consumidora (Racion.)- 1 Min.'),
('FEC1X', 'Freqüência Equivalente de Interrupção por Unid. Cons. Fat. Externos - 1 Min'),
('FECI', 'Freqüência Equivalente de Interrupção por Unid. Cons. Decor.Rede Própria - 3 Min'),
('FECINC', 'FEC de interrup. origem interna ao Sist. de Dist. não progr. e ocor. Dia Crítico'),
('FECIND', 'FEC interrup origem interna, não programada e não expurgavel'),
('FECINE', 'FEC interrup. origem interna, não progr. e ocor. Sit. Emerg, n ocor critico.'),
('FECINO', 'FEC interrup. origem interna não progr. Racionamento e ONS, n ocor dia critico.'),
('FECIP', 'FEC de interrupção de origem interna ao Sist. de Dist. e programada'),
('FECIPC', 'FEC interrup. origem inter. ao sist distr, prog. e ocorr. em dia crítico'),
('FECR', 'Freqüência Equivalente de Interrupção por Unidade Consumidora (Racion.)- 3 Min.'),
('FECX', 'Freqüência Equivalente de Interrupção por Unid. Cons. Decor.Fat.Externos - 3 Min'),
('FECXN', 'FEC de interrupção de origem externa ao Sist. de Dist. e não programada'),
('FECXNC', 'FEC interrup. origem ext. ao sist distr, não prog. e ocorr. em dia crítico'),
('FECXP', 'FEC de interrupção de origem externa ao Sist. de Dist. e programada'),
('FECXPC', 'FEC interrup. origem ext. ao sist distr, prog. e ocorr. em dia crítico'),
('FICVLD', 'Valor apurado do indicador FIC'),
('FICVLDA', 'Valor apurado do indicador FIC'),
('FICVLDT', 'Valor apurado do indicador FIC'),
('FQACCAPDO', 'Taxa de frequência de acidentados com lesão com afastamento - Próprio'),
('FQACCAPTP', 'Taxa de frequência de acidentados com lesão com afastamento - Próprio'),
('FQACCATTP', 'Taxa de frequência de acidentados com lesão com afastamento - Terceiri'),
('FQACPDO', 'Taxa de frequencia de acidentes do trabalho - Próprio Doença'),
('FQACPTP', 'Taxa de frequencia de acidentes do trabalho - Próprio Típico'),
('FQACSAPDO', 'Taxa de frequência de acidentados com lesão sem afastamento - Próprio'),
('FQACSAPTP', 'Taxa de frequência de acidentados com lesão sem afastamento - Próprio'),
('FQACSATTP', 'Taxa de frequência de acidentados com lesão sem afastamento - Terceiri'),
('FQACTTP', 'Taxa de frequencia de acidentes do trabalho - Terceirizado Típico'),
('GRVACPDO', 'Taxa de gravidade de acidentes do trabalho - Próprio Doença'),
('GRVACPTP', 'Taxa de gravidade de acidentes do trabalho - Próprio Típico'),
('GRVACTTP', 'Taxa de gravidade de acidentes do trabalho - Terceirizado Típico'),
('HHRISACP', 'Horas-Homem de exposição ao risco de acidentes - Próprio'),
('HHRISACT', 'Horas-Homem de exposição ao risco de acidentes - Terceirizado'),
('ICC', 'Índices de Unidades Consumidoras com Tensão Crítica'),
('ICOM1', 'Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Comercial'),
('ICOM12', 'Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Comercial'),
('ICOM18', 'Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Comercial'),
('ICOM21', 'Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Comercial'),
('ICOM24', 'Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Comercial'),
('ICOM3', 'Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Comercial'),
('ICOM6', 'Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Comercial'),
('ICOMCRT', 'Quant. de unid. da classe Comercial susp. inadimplência no mês de ref.'),
('ICPROP1', 'Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Consumo Próp.'),
('ICPROP12', 'Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Consumo Próp.'),
('ICPROP18', 'Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Consumo Próp.'),
('ICPROP21', 'Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Consumo Próp.'),
('ICPROP24', 'Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Consumo Próp.'),
('ICPROP3', 'Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Consumo Próp.'),
('ICPROP6', 'Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Consumo Próp.'),
('ICPROPCRT', 'Quant. de unid. da classe Consumo Próp. susp. inadimplência no mês de ref.'),
('IIND1', 'Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Industrial'),
('IIND12', 'Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Industrial'),
('IIND18', 'Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Industrial'),
('IIND21', 'Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Industrial'),
('IIND24', 'Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Industrial'),
('IIND3', 'Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Industrial'),
('IIND6', 'Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Industrial'),
('IINDCRT', 'Quant. de unid. da classe Industrial susp. inadimplência no mês de ref.'),
('IIPUB1', 'Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Iluminação Púb.'),
('IIPUB12', 'Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Iluminação Púb.'),
('IIPUB18', 'Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Iluminação Púb.'),
('IIPUB21', 'Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Iluminação Púb.'),
('IIPUB24', 'Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Iluminação Púb.'),
('IIPUB3', 'Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Iluminação Púb.'),
('IIPUB6', 'Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Iluminação Púb.'),
('IIPUBCRT', 'Quant. de unid. da classe Iluminação Púb. susp. inadimplência no mês de ref.'),
('IPPUB1', 'Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Poder Púb.'),
('IPPUB12', 'Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Poder Púb.'),
('IPPUB18', 'Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Poder Púb.'),
('IPPUB21', 'Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Poder Púb.'),
('IPPUB24', 'Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Poder Púb.'),
('IPPUB3', 'Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Poder Púb.'),
('IPPUB6', 'Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Poder Púb.'),
('IPPUBCRT', 'Quant. de unid. da classe Poder Púb. susp. inadimplência no mês de ref.'),
('IRESBR1', 'Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Resid. Baixa R.'),
('IRESBR12', 'Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Resid. Baixa R.'),
('IRESBR18', 'Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Resid. Baixa R.'),
('IRESBR21', 'Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Resid. Baixa R.'),
('IRESBR24', 'Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Resid. Baixa R.'),
('IRESBR3', 'Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Resid. Baixa R.'),
('IRESBR6', 'Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Resid. Baixa R.'),
('IRESBRCRT', 'Quant. de unid. da classe Resid. Baixa R. susp. inadimplência no mês de ref.'),
('IRESTOT1', 'Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Resid. Total'),
('IRESTOT12', 'Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Resid. Total'),
('IRESTOT18', 'Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Resid. Total'),
('IRESTOT21', 'Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Resid. Total'),
('IRESTOT24', 'Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Resid. Total'),
('IRESTOT3', 'Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Resid. Total'),
('IRESTOT6', 'Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Resid. Total'),
('IRESTOTCRT', 'Quant. de unid. da classe Resid. Total susp. inadimplência no mês de ref.'),
('IRUR1', 'Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Rural'),
('IRUR12', 'Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Rural'),
('IRUR18', 'Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Rural'),
('IRUR21', 'Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Rural'),
('IRUR24', 'Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Rural'),
('IRUR3', 'Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Rural'),
('IRUR6', 'Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Rural'),
('IRURCRT', 'Quant. de unid. da classe Rural susp. inadimplência no mês de ref.'),
('ISERPUB1', 'Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. classe Serviço Púb.'),
('ISERPUB12', 'Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. classe Serviço Púb.'),
('ISERPUB18', 'Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. classe Serviço Púb.'),
('ISERPUB21', 'Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. classe Serviço Púb.'),
('ISERPUB24', 'Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. classe Serviço Púb.'),
('ISERPUB3', 'Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. classe Serviço Púb.'),
('ISERPUB6', 'Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. classe Serviço Púb.'),
('ISERPUBCRT', 'Quant. de unid. da classe Serviço Púb. susp. inadimplência no mês de ref.'),
('ITOT1', 'Perc. da rec. fat. 1° mês ant. não receb. no mês de ref. todos os consumidores'),
('ITOT12', 'Perc. da rec. fat. 12° mês ant. não receb. no mês de ref. todos os consumidores'),
('ITOT18', 'Perc. da rec. fat. 18° mês ant. não receb. no mês de ref. todos os consumidores'),
('ITOT21', 'Perc. da rec. fat. 21° mês ant. não receb. no mês de ref. todos os consumidores'),
('ITOT24', 'Perc. da rec. fat. 24° mês ant. não receb. no mês de ref. todos os consumidores'),
('ITOT3', 'Perc. da rec. fat. 3° mês ant. não receb. no mês de ref. todos os consumidores'),
('ITOT6', 'Perc. da rec. fat. 6° mês ant. não receb. no mês de ref. todos os consumidores'),
('ITOTCRT', 'Quant. total de unid. consumidoras susp. inadimplência no mês de referência'),
('K3', 'Valor do encargo de uso do sistema de distribuição'),
('LOCUC', 'Localização da Unidade Consumidora'),
('LOCUCA', 'Localização da Unidade Consumidora'),
('LOCUCT', 'Localização da Unidade Consumidora'),
('NACCAPDO', 'Número de acidentados com lesão e com afastamento - Próprio Doença'),
('NACCAPTJ', 'Número de acidentados com lesão e com afastamento - Próprio Trajeto'),
('NACCAPTP', 'Número de acidentados com lesão e com afastamento - Próprio Típico'),
('NACCATDO', 'Número de acidentados com lesão e com afastamento - Terceirizado Doença'),
('NACCATTJ', 'Número de acidentados com lesão e com afastamento - Terceirizado Trajet'),
('NACCATTP', 'Número de acidentados com lesão e com afastamento - Terceirizado Típico'),
('NACPDO', 'Número de acidentes do trabalho - Próprio Doença'),
('NACPTJ', 'Número de acidentes do trabalho - Próprio Trajeto'),
('NACPTP', 'Número de acidentes do trabalho - Próprio Típico'),
('NACSAPDO', 'Número de acidentados com lesão e sem afastamento - Próprio Doença'),
('NACSAPTJ', 'Número de acidentados com lesão e sem afastamento - Próprio Trajeto'),
('NACSAPTP', 'Número de acidentados com lesão e sem afastamento - Próprio Típico'),
('NACSATDO', 'Número de acidentados com lesão e sem afastamento - Terceirizado Doença'),
('NACSATTJ', 'Número de acidentados com lesão e sem afastamento - Terceirizado Trajet'),
('NACSATTP', 'Número de acidentados com lesão e sem afastamento - Terceirizado Típico'),
('NACTDO', 'Número de acidentes do trabalho - Terceirizado Doença'),
('NACTER', 'Número de acidentes com terceiros envolvendo a rede elétrica e demais instalaçõe'),
('NACTERANT', 'Nº acid terc rede e demais instal - Antena de TV'),
('NACTERCFE', 'Nº acid terc rede e demais instal - Cabo energizado no solo ou falha de equip'),
('NACTERCHO', 'Nº acid terc rede e demais instal - Choque elétrico por contato'),
('NACTERCLN', 'Nº acid terc rede e demais instal - Ligações clandestinas'),
('NACTERCMP', 'Nº acid terc rede e demais instal - Construção e manutenção predial'),
('NACTERFUR', 'Nº acid terc rede e demais instal - Furto de cabos e/ou outros equipamentos'),
('NACTERGUI', 'Nº acid terc rede e demais instal - Operação de guindaste'),
('NACTEROUT', 'Nº acid terc rede e demais instal - Outros.'),
('NACTERPIP', 'Nº acid terc rede e demais instal - Pipa'),
('NACTERPOD', 'Nº acid terc rede e demais instal - Poda de árvore'),
('NACTERPST', 'Nº acid terc rede e demais instal - Abalroamento de poste e/ou demais instal.'),
('NACTERTVC', 'Nº acid terc rede e demais instal - Serviços de TV a cabo e telefonia'),
('NACTTJ', 'Número de acidentes do trabalho - Terceirizado Trajeto'),
('NACTTP', 'Número de acidentes do trabalho - Terceirizado Típico'),
('NDIACRI', 'Número de dias críticos verificados no ano'),
('NEMPRP', 'Números de Empregados - Próprio'),
('NEMPRT', 'Números de Empregados - Terceirizado'),
('NIE', 'Número de Ocorreências Emergenciais com Interrupções'),
('NMOFUPR', 'Número de mortes de decorrentes de acidentes do trabalho (funcionários próprios)'),
('NMOFUTE', 'Número de mortes decorrentes de acidentes do trabalho (funcionários terceirizado'),
('NMOPDO', 'Número de mortes de decorrentes de acidentes do trabalho - Próprio Doença'),
('NMOPTJ', 'Número de mortes de decorrentes de acidentes do trabalho - Próprio Trajet'),
('NMOPTP', 'Número de mortes de decorrentes de acidentes do trabalho - Próprio Típico'),
('NMOTDO', 'Número de mortes de decorrentes de acidentes do trabalho - Terceirizado Doença'),
('NMOTER', 'Número de mortes decorrentes de acidentes com terceiros envolvendo a rede elétri'),
('NMOTERANT', 'Nº mortes terc rede e demais instal - Antena de TV'),
('NMOTERCFE', 'Nº mortes terc rede e demais instal - Cabo energizado no solo ou falha de equip'),
('NMOTERCHO', 'Nº mortes terc rede e demais instal - Choque elétrico por contato'),
('NMOTERCLN', 'Nº mortes terc rede e demais instal - Ligações clandestinas'),
('NMOTERCMP', 'Nº mortes terc rede e demais instal - Construção e manutenção predial'),
('NMOTERFUR', 'Nº mortes terc rede e demais instal - Furto de cabos e/ou outros equip'),
('NMOTERGUI', 'Nº mortes terc rede e demais instal - Operação de guindaste'),
('NMOTEROUT', 'Nº mortes terc rede e demais instal - Outros.'),
('NMOTERPIP', 'Nº mortes terc rede e demais instal - Pipa'),
('NMOTERPOD', 'Nº mortes terc rede e demais instal - Poda de árvore'),
('NMOTERPST', 'Nº mortes terc rede e demais instal - Abalroamento de poste e/ou demais inst'),
('NMOTERTVC', 'Nº mortes terc rede e demais instal - Serviços de TV a cabo e telef'),
('NMOTTJ', 'Número de mortes de decorrentes de acidentes do trabalho - Terceirizado Trajeto'),
('NMOTTP', 'Número de mortes de decorrentes de acidentes do trabalho - Terceirizado Típico'),
('NUCTCO', 'Total de unidades consumidoras comercial MT e BT'),
('NUCTIN', 'Total de unidades consumidoras industrial MT e BT'),
('NUCTOU', 'Total de unidades consumidoras de outras classes  MT e BT'),
('NUCTRE', 'Total de unidades consumidoras residencial MT e BT'),
('NUCTRU', 'Total de unidades consumidoras rural MT e BT'),
('NUMCON', 'Número de Consumidores do Conjunto no Período'),
('NUMCONSAGT', 'Número de Consumidores do Distribuidor no Período'),
('NUMOCORR', 'Número de Ocorrencias Emergenciais no Conjunto no Período'),
('PGUCAT', 'Valor pago a UCs AT por violacao dos limites de continuidade no mes'),
('PGUCATA', 'Valor pago a UCs AT por violacao dos limites de cont no ano'),
('PGUCATDC', 'Valor pago as UCs AT por violacao dos limites de DICRI'),
('PGUCATT', 'Valor pago a UCs AT por violacao dos limites de cont no trimestre'),
('PGUCBTNU', 'Valor pago a UCs BT não urbanas por violacao dos limites de cont no mes'),
('PGUCBTNUA', 'Valor pago a UCs BT não urbanas por violacao dos limites de cont no ano'),
('PGUCBTNUDC', 'Valor pago as UCs BT não urbanas por violacao dos limites de DICRI'),
('PGUCBTNUDS', 'Valor pago as UCs BT não urbanas por violacao dos limites de DISE'),
('PGUCBTNUT', 'Valor pago a UCs BT não urbanas por violacao dos limites de cont no trimestre'),
('PGUCBTU', 'Valor pago a UCs BT urbanas por violacao dos limites de continuidade no mes'),
('PGUCBTUA', 'Valor pago a UCs BT urbanas por violacao dos limites de cont no ano'),
('PGUCBTUDC', 'Valor pago as UCs BT urbanas por violacao dos limites de DICRI'),
('PGUCBTUDS', 'Valor pago as UCs BT urbanas por violacao dos limites de DISE'),
('PGUCBTUT', 'Valor pago a UCs BT urbanas por violacao dos limites de cont no trimestre'),
('PGUCMTNU', 'Valor pago a UCs MT não urbanas por violacao dos limites de cont no mes'),
('PGUCMTNUA', 'Valor pago a UCs MT não urbanas por violacao dos limites de cont no ano'),
('PGUCMTNUDC', 'Valor pago as UCs MT não urbanas por violacao dos limites de DICRI'),
('PGUCMTNUDS', 'Valor pago as UCs MT não urbanas por violacao dos limites de DISE'),
('PGUCMTNUT', 'Valor pago a UCs MT não urbanas por violacao dos limites de cont no trimestre'),
('PGUCMTU', 'Valor pago a UCs MT urbanas por violacao dos limites de continuidade no mes'),
('PGUCMTUA', 'Valor pago a UCs MT urbanas por violacao dos limites de cont no ano'),
('PGUCMTUDC', 'Valor pago as UCs MT urbanas por violacao dos limites de DICRI'),
('PGUCMTUDS', 'Valor pago as UCs MT urbanas por violacao dos limites de DISE'),
('PGUCMTUT', 'Valor pago a UCs MT urbanas por violacao dos limites de cont no trimestre'),
('PGUCTRP', 'Valor pago a UCs por violacao dos limites de tensao em regime permanente'),
('PGUCTRPA', 'Valor pago a UCs por violação limites de tensão em regime permmed.amostral'),
('PGUCTRPE', 'Valor pago a UCs por violação limites de tensão em regime permmed.eventual'),
('PGUCTRPP', 'Valor pago a UCs por violação limites de tensão em regime permmed.amostral'),
('PGUGAT', 'Valor pago a UGs AT por violacao dos limites de continuidade no mes'),
('PGUGATA', 'Valor pago a UGs AT por violacao dos limites de cont no ano'),
('PGUGATDC', 'Valor pago as UGs AT por violacao dos limites de DICRI'),
('PGUGATT', 'Valor pago a UGs AT por violacao dos limites de cont no trimestre'),
('PGUGBTNU', 'Valor pago a UGs BT não urbanas por violacao dos limites de cont no mes'),
('PGUGBTNUA', 'Valor pago a UGs BT não urbanas por violacao dos limites de cont no ano'),
('PGUGBTNUDC', 'Valor pago as UGs BT não urbanas por violacao dos limites de DICRI'),
('PGUGBTNUDS', 'Valor pago as UGs BT não urbanas por violacao dos limites de DISE'),
('PGUGBTNUT', 'Valor pago a UGs BT não urbanas por violacao dos limites de cont no trimestre'),
('PGUGBTU', 'Valor pago a UGs BT urbanas por violacao dos limites de continuidade no mes'),
('PGUGBTUA', 'Valor pago a UGs BT urbanas por violacao dos limites de cont no ano'),
('PGUGBTUDC', 'Valor pago as UGs BT urbanas por violacao dos limites de DICRI'),
('PGUGBTUDS', 'Valor pago as UGs BT urbanas por violacao dos limites de DISE'),
('PGUGBTUT', 'Valor pago a UGs BT urbanas por violacao dos limites de cont no trimestre'),
('PGUGMTNU', 'Valor pago a UGs MT não urbanas por violacao dos limites de cont no mes'),
('PGUGMTNUA', 'Valor pago a UGs MT não urbanas por violacao dos limites de cont no ano'),
('PGUGMTNUDC', 'Valor pago as UGs MT não urbanas por violacao dos limites de DICRI'),
('PGUGMTNUDS', 'Valor pago as UGs MT não urbanas por violacao dos limites de DISE'),
('PGUGMTNUT', 'Valor pago a UGs MT não urbanas por violacao dos limites de cont no trimestre'),
('PGUGMTU', 'Valor pago a UGs MT urbanas por violacao dos limites de continuidade no mes'),
('PGUGMTUA', 'Valor pago a UGs MT urbanas por violacao dos limites de cont no ano'),
('PGUGMTUDC', 'Valor pago as UGs MT urbanas por violacao dos limites de DICRI'),
('PGUGMTUDS', 'Valor pago as UGs MT urbanas por violacao dos limites de DISE'),
('PGUGMTUT', 'Valor pago a UGs MT urbanas por violacao dos limites de cont no trimestre'),
('PMAFEDMED', 'Prazo Médio de solicitações de aferição dos medidores (art. 137)'),
('PMANPROJ', 'Prazo Médio de informação do resultado da análise do projeto (art. 27-B)'),
('PMCMSNOBRA', 'Prazo médio de Comissionamento das obras. (art. 37)'),
('PMESTPROJ', 'Prazo Médio de estudos, orçamentos e projetos por obras (art. 32)'),
('PMINFORM', 'Prazo Médio de informação da relação dos atendimentos (art. 199)'),
('PMLIGA', 'Prazo Médio de ligação de unidade consumidora do grupo A (art. 31)'),
('PMLIGBRR', 'Prazo Médio de ligação de consumidor do grupo B em área rural (art. 31)'),
('PMLIGBUB', 'Prazo Médio de ligação de consumidor do grupo B em área urbana (art. 31)'),
('PMNVCMSN', 'Prazo médio de Novo comissionamento quando de reprovação. (art. 37)'),
('PMOBGERAIS', 'Prazo médio de Conclusão de obra não abrang. nos inc. I e II do art. 34.'),
('PMOBRA', 'Prazo Médio de Início das Obras (art. 34)'),
('PMOBRAPRIM', 'Prazo médio de Conclusão das obras de até 1 km na rede  prim. (art. 34)'),
('PMOBRASEC', 'Prazo médio de Conclusão das obras na rede tensão sec. (art. 34)'),
('PMPGTORSC', 'Prazo Médio de ressarc. por meio do pgto, conserto ou subst. (art. 208)'),
('PMRCLCOBR', 'Prazo Médio de reclamação de cobrança ou devol. de diferenças (art. 133)'),
('PMRCLDANO', 'Prazo Médio de solução ref. à danos não elétricos reclamados (art. 197)'),
('PMRCLVISTC', 'Prazo Médio de solução de reclamação com visita técnica (art. 197)'),
('PMREANPROJ', 'Prazo Médio de reanálise do projeto por falta de informação (art. 27-B)'),
('PMRELIGIDV', 'Prazo Médio de religação por suspensão indevida do fornec. (art. 176)'),
('PMRELNORRR', 'Prazo Médio de religação em área rural (art. 176)'),
('PMRELNORUB', 'Prazo Médio de religação em área urbana (art. 176)'),
('PMRELURGRR', 'Prazo Médio de religação de emergência em área rural (art. 176)'),
('PMRELURGUB', 'Prazo Médio de religação de emergência em área urbana (art. 176)'),
('PMRESULRSC', 'Prazo Médio de resultado da solicitação de ressarcimento (art. 207)'),
('PMSUBSTMED', 'Prazo Médio de substituição do medidor com defeito (art. 115)'),
('PMVISTRR', 'Prazo Médio de vistoria de unidade consumidora de área rural (art. 30)'),
('PMVISTUB', 'Prazo médio de vistoria de unidade consumidora de área urbana (art. 30)'),
('PMVRFRESFR', 'Prazo Médio de verif. de equip. de resfriamento por ressarc. (art. 206)'),
('PMVRFRSC', 'Prazo Médio de verif. de equip. por ressarc. de dano elétrico (art. 206)'),
('PNIE', 'Percentual do Número de Ocorreências Emergenciais com Interrupções'),
('PNIT', 'Potência instalada de transformadores de distribuição, em kVA, de todos os'),
('PNITT', 'Potencia Instalada de transformadores de distribuição em kVA'),
('QSAFEDMED', 'Quantidade de solicitações de aferição dos medidores (art. 137)'),
('QSANPROJ', 'Quantidade de informação do resultado da análise do projeto (art. 27-B)'),
('QSCMSNOBRA', 'Quantidade de Comissionamento das obras. (art. 37)'),
('QSESTPROJ', 'Quantidade de estudos, orçamentos e projetos por obras (art. 32)'),
('QSINFORM', 'Quantidade de informação da relação dos atendimentos (art. 199)'),
('QSLIGA', 'Quantidade de ligação de unidade consumidora do grupo A (art. 31)'),
('QSLIGBRR', 'Quantidade de ligação de consumidor do grupo B em área rural (art. 31)'),
('QSLIGBUB', 'Quantidade de ligação de consumidor do grupo B em área urbana (art. 31)'),
('QSNVCMSN', 'Quantidade de Novo comissionamento quando de reprovação. (art. 37)'),
('QSOBGERAIS', 'Quantidade de Conclusão de obra não abrang. nos inc. I e II do art. 34.'),
('QSOBRA', 'Quantidade de Início das Obras (art. 34)'),
('QSOBRAPRIM', 'Quantidade de Conclusão das obras de até 1 km na rede prim. (art. 34)'),
('QSOBRASEC', 'Quantidade de Conclusão das obras na rede tensão sec. (art. 34)'),
('QSPGTORSC', 'Quantidade de ressarc. por meio do pgto, conserto ou subst. (art. 208)'),
('QSRCLCOBR', 'Quantidade de reclamação de cobrança ou devol. de diferenças (art. 133)'),
('QSRCLDANO', 'Quantidade de solução ref. à danos não elétricos reclamados (art. 197)'),
('QSRCLVISTC', 'Quantidade de solução de reclamação com visita técnica (art. 197)'),
('QSREANPROJ', 'Quantidade de reanálise do projeto por falta de informação (art. 27-B)'),
('QSRELIGIDV', 'Quantidade de religação por suspensão indevida do fornec. (art. 176)'),
('QSRELNORRR', 'Quantidade de religação em área rural (art. 176)'),
('QSRELNORUB', 'Quantidade de religação em área urbana (art. 176)'),
('QSRELURGRR', 'Quantidade de religação de emergência em área rural (art. 176)'),
('QSRELURGUB', 'Quantidade de religação de emergência em área urbana (art. 176)'),
('QSRESULRSC', 'Quantidade de resultado da solicitação de ressarcimento (art. 207)'),
('QSSUBSTMED', 'Quantidade de substituição do medidor com defeito (art. 115)'),
('QSVISTRR', 'Quantidade de vistoria de unidade consumidora de área rural (art. 30)'),
('QSVISTUB', 'Quantidade de vistoria de unidade consumidora de área urbana (art. 30)'),
('QSVRFRESFR', 'Quantidade de verif. de equip. de resfriamento por ressarc. (art. 206)'),
('QSVRFRSC', 'Quantidade de verif. de equip. por ressarc. de dano elétrico (art. 206)'),
('QTUCAT', 'Qtde de UCs AT compensadas por violacao dos limites de continuidade no mes'),
('QTUCATA', 'Qtde de UCs AT compens por violacao dos limites de cont no ano'),
('QTUCATDC', 'Qtde de UCs AT comp por violacao dos limites de DICRI'),
('QTUCATT', 'Qtde de UCs AT compens por violacao dos limites de cont no trimestre'),
('QTUCBTNU', 'Qtde de UCs BT não urbanas comp por violacao dos limites de cont no mes'),
('QTUCBTNUA', 'Qtde de UCs BT não urbanas comp por violacao dos limites de cont no ano'),
('QTUCBTNUDC', 'Qtde de UCs BT não urbanas comp por violacao dos limites de DICRI'),
('QTUCBTNUDS', 'Qtde de UCs BT não urbanas comp por violacao dos limites de DISE'),
('QTUCBTNUT', 'Qtde de UCs BT não urbanas comp por violacao dos limites de cont no trimestre'),
('QTUCBTU', 'Qtde de UCs BT urbanas compensadas por violacao dos limites de cont no mes'),
('QTUCBTUA', 'Qtde de UCs BT urbanas compens por violacao dos limites de cont no ano'),
('QTUCBTUDC', 'Qtde de UCs BT urbanas comp por violacao dos limites de DICRI'),
('QTUCBTUDS', 'Qtde de UCs BT urbanas comp por violacao dos limites de DISE'),
('QTUCBTUT', 'Qtde de UCs BT urbanas compens por violacao dos limites de cont no trimestre'),
('QTUCMTNU', 'Qtde de UCs MT não urbanas comp por violacao dos limites de cont no mes'),
('QTUCMTNUA', 'Qtde de UCs MT não urbanas comp por violacao dos limites de cont no ano'),
('QTUCMTNUDC', 'Qtde de UCs MT não urbanas comp por violacao dos limites de DICRI'),
('QTUCMTNUDS', 'Qtde de UCs MT não urbanas comp por violacao dos limites de DISE'),
('QTUCMTNUT', 'Qtde de UCs MT não urbanas comp por violacao dos limites de cont no trimestre'),
('QTUCMTU', 'Qtde de UCs MT urbanas compensadas por violacao dos limites de cont no mes'),
('QTUCMTUA', 'Qtde de UCs MT urbanas compens por violacao dos limites de cont no ano'),
('QTUCMTUDC', 'Qtde de UCs MT urbanas comp por violacao dos limites de DICRI'),
('QTUCMTUDS', 'Qtde de UCs MT urbanas comp por violacao dos limites de DISE'),
('QTUCMTUT', 'Qtde de UCs MT urbanas compens por violacao dos limites de cont no trimestre'),
('QTUCTRP', 'Qtde de UCs comp por violacao dos limites de tensao em regime permanente'),
('QTUCTRPA', 'Qtde de UC compens.-violação limites de tensão em regime permmed.amostral'),
('QTUCTRPE', 'Qtde de UC compens.-violação limites de tensão em regime permmed.eventual'),
('QTUCTRPP', 'Qtde de UC compens.-violação limites de tensão em regime permmed.perman.'),
('QTUGAT', 'Qtde de UGs AT compensadas por violacao dos limites de continuidade no mes'),
('QTUGATA', 'Qtde de UGs AT compens por violacao dos limites de cont no ano'),
('QTUGATDC', 'Qtde de UGs AT comp por violacao dos limites de DICRI'),
('QTUGATT', 'Qtde de UGs AT compens por violacao dos limites de cont no trimestre'),
('QTUGBTNU', 'Qtde de UGs BT não urbanas comp por violacao dos limites de cont no mes'),
('QTUGBTNUA', 'Qtde de UGs BT não urbanas comp por violacao dos limites de cont no ano'),
('QTUGBTNUDC', 'Qtde de UGs BT não urbanas comp por violacao dos limites de DICRI'),
('QTUGBTNUDS', 'Qtde de UGs BT não urbanas comp por violacao dos limites de DISE'),
('QTUGBTNUT', 'Qtde de UGs BT não urbanas comp por violacao dos limites de cont no trimestre'),
('QTUGBTU', 'Qtde de UGs BT urbanas compensadas por violacao dos limites de cont no mes'),
('QTUGBTUA', 'Qtde de UGs BT urbanas compens por violacao dos limites de cont no ano'),
('QTUGBTUDC', 'Qtde de UGs BT urbanas comp por violacao dos limites de DICRI'),
('QTUGBTUDS', 'Qtde de UGs BT urbanas comp por violacao dos limites de DISE'),
('QTUGBTUT', 'Qtde de UGs BT urbanas compens por violacao dos limites de cont no trimestre'),
('QTUGMTNU', 'Qtde de UGs MT não urbanas comp por violacao dos limites de cont no mes'),
('QTUGMTNUA', 'Qtde de UGs MT não urbanas comp por violacao dos limites de cont no ano'),
('QTUGMTNUDC', 'Qtde de UGs MT não urbanas comp por violacao dos limites de DICRI'),
('QTUGMTNUDS', 'Valor pago as UGs BT urbanas por violacao dos limites de DISE'),
('QTUGMTNUT', 'Qtde de UGs MT não urbanas comp por violacao dos limites de cont no trimestre'),
('QTUGMTU', 'Qtde de UGs MT urbanas compensadas por violacao dos limites de cont no mes'),
('QTUGMTUA', 'Qtde de UGs MT urbanas compens por violacao dos limites de cont no ano'),
('QTUGMTUDC', 'Qtde de UGs MT urbanas comp por violacao dos limites de DICRI'),
('QTUGMTUDS', 'Qtde de UGs MT urbanas comp por violacao dos limites de DISE'),
('QTUGMTUT', 'Qtde de UGs MT urbanas compens por violacao dos limites de cont no trimestre'),
('QVAFEDMED', 'Quant. Prazos Viol. de solicitações de aferição dos medidores (art. 137)'),
('QVANPROJ', 'Quant. Prazos Viol. de informação do resultado da análise do projeto (art. 27-B)'),
('QVCMSNOBRA', 'Quant. Prazos Viol. de Comissionamento das obras. (art. 37)'),
('QVESTPROJ', 'Quant. Prazos Viol. de estudos, orçamentos e projetos por obras (art. 32)'),
('QVINFORM', 'Quant. Prazos Viol. de informação da relação dos atendimentos (art. 199)'),
('QVLIGA', 'Quant. Prazos Viol. de ligação de unidade consumidora do grupo A (art. 31)'),
('QVLIGBRR', 'Quant. Prazos Viol. de ligação de consumidor do grupo B em área rural (art. 31)'),
('QVLIGBUB', 'Quant. Prazos Viol. de ligação de consumidor do grupo B em área urbana (art. 31)'),
('QVNVCMSN', 'Quant. Prazos Viol. de Novo comissionamento quando de reprovação. (art. 37)'),
('QVOBGERAIS', 'Quant. Prazos Viol. de Conclusão de obra não abrang. nos inc. I e II do art. 34.'),
('QVOBRA', 'Quant. Prazos Viol. de Início das Obras (art. 34)'),
('QVOBRAPRIM', 'Quant. Prazos Viol. de Conclusão das obras de até 1 km na rede prim. (art. 34)'),
('QVOBRASEC', 'Quant. Prazos Viol. de Conclusão das obras na rede tensão sec. (art. 34)'),
('QVPGTORSC', 'Quant. Prazos Viol. de ressarc. por meio do pgto, conserto ou subst. (art. 208)'),
('QVRCLCOBR', 'Quant. Prazos Viol. de reclamação de cobrança ou devol. de diferenças (art. 133)'),
('QVRCLDANO', 'Quant. Prazos Viol. de solução ref. à danos não elétricos reclamados (art. 197)'),
('QVRCLVISTC', 'Quant. Prazos Viol. de solução de reclamação com visita técnica (art. 197)'),
('QVREANPROJ', 'Quant. Prazos Viol. de reanálise do projeto por falta de informação (art. 27-B)'),
('QVRELIGIDV', 'Quant. Prazos Viol. de religação por suspensão indevida do fornec. (art. 176)'),
('QVRELNORRR', 'Quant. Prazos Viol. de religação em área rural (art. 176)'),
('QVRELNORUB', 'Quant. Prazos Viol. de religação em área urbana (art. 176)'),
('QVRELURGRR', 'Quant. Prazos Viol. de religação de emergência em área rural (art. 176)'),
('QVRELURGUB', 'Quant. Prazos Viol. de religação de emergência em área urbana (art. 176)'),
('QVRESULRSC', 'Quant. Prazos Viol. de resultado da solicitação de ressarcimento (art. 207)'),
('QVSUBSTMED', 'Quant. Prazos Viol. de substituição do medidor com defeito (art. 115)'),
('QVVISTRR', 'Quant. Prazos Viol. vistoria de unidade consumidora de área rural (art. 30)'),
('QVVISTUB', 'Quant. Prazos Viol. de vistoria de unidade consumidora de área urbana (art. 30)'),
('QVVRFRESFR', 'Quant. Prazos Viol. de verif. de equip. de resfriamento por ressarc. (art. 206)'),
('QVVRFRSC', 'Quant. Prazos Viol. de verif. de equip. por ressarc. de dano elétrico (art. 206)'),
('TI1', 'Tensão Interna'),
('TMD', 'Tempo Médio de Deslocamento'),
('TME', 'Tempo Médio de Execução'),
('TMM', 'Tempo Médio de Mobilização'),
('TMP', 'Tempo Médio de Preparação'),
('TNS', 'Tensão'),
('TNSA', 'Tensão'),
('TNST', 'Tensão'),
('TSC', 'Tipo de sistema do conjunto, 1: Sistema Interligado'),
('TSCT', 'Tipo de sistema do conjunto. 1: Interligado, 2: Isolado'),
('TXFQAC', 'Taxa de frequencia de acidentes do trabalho'),
('TXGRAC', 'Taxa de gravidade de acidentes do trabalho'),
('VLCLACRI', 'Valor utilizado no ano para identificar se um dia pode ser classificado critico')
ON CONFLICT (indicator_code) DO UPDATE
SET indicator_description = EXCLUDED.indicator_description;
